// src/app/ysea/page.tsx
"use client";

import { ExternalLinkIcon } from "@chakra-ui/icons";
import {
  Box,
  Button,
  Center,
  Container,
  Flex,
  Heading,
  ListItem,
  SimpleGrid,
  Stack,
  Text,
  UnorderedList,
  VStack,
} from "@chakra-ui/react";
import { ReactNode } from "react";

export default function Page() {
  return (
    <VStack className="items-center justify-items-center font-[family-name:var(--font-geist-sans)]">
      <Box
        w="full"
        className="flex flex-col row-start-2 items-center sm:items-start"
      >
        {/* Hero Section */}
        <Flex
          w={"full"}
          h={"40vh"}
          backgroundImage={"/campus_bg.jpg"}
          backgroundSize={"cover"}
          backgroundPosition={"top center"}
        >
          <VStack
            w={"full"}
            justify={"center"}
            px={[4, null, null, 8]}
            bgGradient={"linear(to-r, blackAlpha.600, transparent)"}
          >
            <Stack
              maxW={"3xl"}
              align={"flex-start"}
              spacing={4}
              textAlign="center"
              borderRadius={10}
              p={4}
              py={6}
              bgColor={"blackAlpha.500"}
            >
              <Text
                color={"white"}
                fontWeight={700}
                lineHeight={1.2}
                fontSize={["3xl", null, null, "4xl"]}
              >
                MCBIOS Young Scientist Excellence Awards
              </Text>
            </Stack>
          </VStack>
        </Flex>
        {/* YSEA Instructions */}
        <Box bgColor="blue.800" position={"relative"} w="full">
          <Container>
            <Stack direction={{ base: "column", lg: "row" }} my={12}>
              <Stack
                color={"blue.100"}
                justify={{ lg: "center" }}
                py={{ base: 4, md: 20, xl: 50 }}
                gap={5}
              >
                <Box mb={{ base: 8, md: 20 }}>
                  <Text
                    fontFamily={"heading"}
                    fontWeight={700}
                    textTransform={"uppercase"}
                    mb={3}
                    fontSize={"xl"}
                    color={"blue.100"}
                    decoration="underline"
                  >
                    Deadline: January 30th, 2025
                  </Text>
                  <Heading
                    color={"white"}
                    mb={5}
                    fontSize={{ base: "3xl", md: "5xl" }}
                  >
                    2025 Young Scientist Excellence Award Applications
                  </Heading>
                  <Center>
                    <Button
                      as="a"
                      size="lg"
                      w="md"
                      // href="https://forms.gle/RVYFXmoodnGdAupX9"
                      // target="_blank"
                      color={"white"}
                      rounded={"full"}
                      alignItems="center"
                      leftIcon={<ExternalLinkIcon />}
                      bg={"blue.600"}
                      disabled
                  >
                      YSEA Application
                    </Button>
                  </Center>
                </Box>

                <SimpleGrid
                  columns={{ base: 1, md: 2 }}
                  spacing={10}
                  mx={{ base: 5, md: 0 }}
                >
                  {blurbs.map((blurb) => (
                    <Box key={blurb.title} w="full">
                      <Text
                        fontFamily={"heading"}
                        fontSize={"3xl"}
                        color={"white"}
                        mb={3}
                      >
                        {blurb.title}
                      </Text>
                      <Text fontSize={"xl"} color={"gray.400"}>
                        {blurb.content}
                      </Text>
                      {blurb.list &&
                        blurb.list.map((item) => (
                          <UnorderedList key={item} my={4}>
                            <ListItem>
                              <Text>{item}</Text>
                            </ListItem>
                          </UnorderedList>
                        ))}
                    </Box>
                  ))}
                </SimpleGrid>
              </Stack>
            </Stack>
          </Container>
        </Box>
      </Box>
    </VStack>
  );
}

const TextHighlight = ({ children }: { children: ReactNode }) => (
  <Text as={"span"} fontWeight={700} color={"white"}>
    {children}
  </Text>
);

const blurbs = [
  {
    title: "Application and Evaluation Process",
    content: (
      <>
        Applications from students and postdoctoral fellows will be rigorously
        evaluated. The <TextHighlight>top four candidates</TextHighlight> will
        be invited to give an oral presentation in a session dedicated to this
        award program.
        <br />
        <br />
        In addition to an abstract, participation in this program requires
        submission of two additional documents: <br />
      </>
    ),
    list: [
      "A description of the innovation of the research (150 words or less).",
      "An explanation of the individual's contribution to the work being presented (150 words or less).",
    ],
  },
  {
    title: "Selection Criteria",
    content: (
      <>
        The selection of the top four candidates is based on an evaluation by
        the MCBIOS board members, who assess{" "}
        <TextHighlight>the quality and impact</TextHighlight> of the research.
        After the oral presentations, a panel of judges (including keynote
        speakers) selects the finalists.
        <br />
        <br /> The primary consideration for awarding is the quality of the
        professional presentation. Applicants demonstrating a multidisciplinary
        contribution and initiative receive preference during the final
        selection process.
      </>
    ),
  },
  {
    title: "Award Announcement",
    content: <>The awards will be announced during the final luncheon.</>,
  },
];

// src/routes/ysea/+page.svelte
<script>
	import AwardPic from '$lib/assets/background/wan-san-yip-ID1yWa1Wpx0-unsplash.jpg';
	import Hero from '../../components/Hero.svelte';
</script>

<svelte:head>
	<title>MCBIOS 2024 | YSEA</title>
</svelte:head>

<div class="w-full justify-center">
	<Hero imageSrc={AwardPic} headerText="MCBIOS YOUNG SCIENTIST EXCELLENCE AWARDS" />
</div>
<div class="w-full justify-center bg-surface-700 shadow-lg py-10 -mt-16">
	<div class="space-y-5 w-11/12 md:w-5/6 mx-auto">
		<p class="text-center blockquote">
			If you are a graduate student or a postdoc, we invite you to apply. If you are a mentor of
			trainees, please encourage your trainees to apply.
		</p>
	</div>
</div>
<div class="w-5/6 mx-auto mt-32 mb-40 block md:flex gap-5">
	<div class="w-full md:w-1/3">
		<h3 class="h3 underline mb-5 text-center">
			2024 Young Scientist Excellence Award Applications
		</h3>
		<p class="text-center">Theme: To be announced</p>
		<p class="text-center">Deadline: To be announced</p>
		<div class="px-auto flex">
			<a
				href="https://bit.ly/MCBIOSYoungScientistAward"
				target="_blank"
				class="btn btn-lg variant-outline-primary my-7 mx-auto">Apply Now</a
			>
		</div>
	</div>
	<div class="w-full md:w-2/3 space-y-3">
		<h3 class="h3">MCBIOS Young Scientist Excellence</h3>
		<p>
			Applications from students and postdoctoral fellows will be rigorously evaluated. The top four
			candidates will be invited to give an oral presentation in a session dedicated to this award
			program. In addition to an abstract, participation in this program requires submission of a
			separate description of the innovation of the research (150 words or less) and the
			individual's contribution to the work being presented (150 words or less). Selection of the
			top four candidates is based on the evaluation of the applications by the MCBIOS board members
			for quality and impact of the research. The finalists are selected by a panel of judges
			(including keynote speakers) after the oral presentations. The quality of the professional
			presentation is the primary consideration for selection of the award recipients. Applicants
			with demonstrated multidisciplinary contribution and initiative are given preference during
			final selection. Announcement of the awards will be made during the final luncheon.
		</p>
	</div>
</div>
