// src/routes/registration/+page.svelte
<script>
	import Abstract from '$lib/assets/background/Chang-Su_abstract.jpg';
	import Hero from '../../components/Hero.svelte';
	let registrationOpen = true;
</script>

<svelte:head>
	<title>MCBIOS 2024 | Registration</title>
</svelte:head>

<Hero imageSrc={Abstract} headerText="Conference Registration" />

<div class="w-9/12 md:w-10/12 grid grid-cols-3 gap-10 gap-y-14 justify-evenly m-auto h-1/4">
	<div class="col-span-3 md:col-span-1 m-auto space-y-4">
		<p class="h3 text-3xl text-center">Information Regarding Registration</p>

		<p class="text-center col-span-3 md:col-span-1 text-lg m-auto">
			Payment is expected at the time of registration (Credit or Debit Card). Demographic
			information gathered during registration will be aggregated and utilized by MCBIOS for grant
			applications. Member's information is never shared or sold.
		</p>
		<p class="text-center col-span-3 md:col-span-1 text-lg m-auto">
			All three types of registration include complimentary 1-year MCBIOS membership, which provides
			access to workshops and collaborative projects hosted by MCBIOS throughout the year.
		</p>
	</div>
	<div class="col-span-3 md:col-span-2 flex m-auto">
		<div
			class="card bg-gradient-to-br from-pink-500 to-violet-500 bg-clip-text text-transparent border-tertiary-500 border-2"
		>
			<header class="card-header text-center"><h3 class="h3">MCBIOS 2024 Registration</h3></header>
			{#if registrationOpen}
				<section class="p-4">
					To register for the 2024 Conference, select your registration type from the list below.
					Secure payment processing powered by Stripe Checkout.
					<div class="flex justify-center">
						<a
							href="#"
							class="btn btn-lg variant-ringed-primary my-5">Registration Closed</a
						>
					</div>
				</section>
			{:else}
				<section class="p-4 text-xl">
					Registration will open up soon, please keep an eye out!
				</section>
			{/if}
		</div>
	</div>
</div>

// src/app/registration/page.tsx
"use client";

import { Link } from "@chakra-ui/next-js";
import {
  Box,
  Button,
  Card,
  CardBody,
  Flex,
  Heading,
  SimpleGrid,
  Stack,
  Text,
  VStack,
} from "@chakra-ui/react";
import localFont from "next/font/local";
import { useState } from "react";

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Page() {
  const [registrationOpen] = useState(true);
  return (
    <VStack className="items-center justify-items-center font-[family-name:var(--font-geist-sans)]">
      <Box
        w="full"
        className="flex flex-col row-start-2 items-center sm:items-start"
      >
        {/* Hero Section */}
        <Flex
          w={"full"}
          h={"40vh"}
          backgroundImage={"/Winter Campus View 2018-4.jpg"}
          backgroundSize={"cover"}
          backgroundPosition={"top center"}
        >
          <VStack
            w={"full"}
            justify={"center"}
            px={[4, null, null, 8]}
            bgGradient={"linear(to-r, blackAlpha.600, transparent)"}
          >
            <Stack
              maxW={"3xl"}
              align={"flex-start"}
              spacing={4}
              textAlign="center"
              borderRadius={10}
              px={[15, null, 20]}
              py={6}
              bgColor={"blackAlpha.500"}
            >
              <Text
                color={"white"}
                fontWeight={700}
                lineHeight={1.2}
                fontSize={["3xl", null, null, "4xl"]}
              >
                Conference Registration
              </Text>
            </Stack>
          </VStack>
        </Flex>
        {/* YSEA Instructions */}
        <SimpleGrid
          w="full"
          mx="auto"
          justifyContent="space-evenly"
          py="20"
          bgGradient="linear(to-br, whiteAlpha.200, whiteAlpha.400, orange.100, blue.300)"
          columns={{ base: 1, lg: 2 }}
          spacing={10}
        >
          <VStack w={{ base: "90%", lg: "75%" }} mx="auto" spacing={5}>
            <Heading size="lg" color="blue.800">
              Information Regarding Registration
            </Heading>
            <Text>
              Payment is expected at the time of registration (Credit or Debit
              Card). Demographic information gathered during registration will
              be aggregated and utilized by MCBIOS for grant applications.
              Member&apos;s information is never shared or sold.
            </Text>
            <Text>
              All three types of registration include complimentary 1-year
              MCBIOS membership, which provides access to workshops and
              collaborative projects hosted by MCBIOS throughout the year.
            </Text>
          </VStack>
          <VStack
            w={{ base: "90%", lg: "50%" }}
            mx="auto"
            justifyContent="space-around"
          >
            <Card
              w={{ base: "full", md: "md" }}
              _hover={{ shadow: "xl", borderColor: "blue.600" }}
              borderColor="blue.400"
              borderWidth={0.5}
            >
              <CardBody>
                <Stack spacing="3">
                  <Heading
                    size="xl"
                    color="blue.800"
                    textAlign="center"
                    className={geistMono.className}
                  >
                    MCBIOS 2025 Registration
                  </Heading>
                  {!registrationOpen ? (
                    <Text textAlign="center">
                      Registration opening soon. Construction is underway!
                    </Text>
                  ) : (
                    <>
                      <Text mx="auto" fontSize="lg">
                        To register for the 2025 Conference, create your MCBIOS
                        account and select your registration type. Secure
                        payment processing powered by Stripe Checkout.
                      </Text>
                      <Button
                        as={Link}
                        mx="auto"
                        href="https://mcbios.com/membership"
                        target="_blank"
                        bg={"blue.400"}
                        rounded={"full"}
                        color={"white"}
                        _hover={{ bg: "blue.500" }}
                      >
                        Register Today!
                      </Button>
                    </>
                  )}
                </Stack>
              </CardBody>
            </Card>
          </VStack>
        </SimpleGrid>
      </Box>
    </VStack>
  );
}
